//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int OrderDetailsID { get; set; }
        public string UserLogin { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
