//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _420_476_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ReviewID { get; set; }
        public byte Score { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string UserLogin { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Reports { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Products Products { get; set; }
    }
}
